### ISSUE TITLE
Provide completion status overview / how to help

### ISSUE THREAD

**Issue by waldyrious** [vfmd/vfmd-test#1]
Since this is the only item in vfmd.org's "Deliverables" section not marked as "Done", it would be nice to provide a list of missing items, and instructions so that those interested could contribute the missing parts in modular fashion.

**Comment by roop** [comment]
Sorry about the delay.

The missing tests are now listed in the [vfmd-tests README](https://github.com/vfmd/vfmd-test/blob/master/README.md#todo). The status now reads "Incomplete" with a link to this TODO.

Many thanks for pointing this out.

**Comment by waldyrious** [comment]
Thanks! For future reference, the TODO information was added in commit 544d650.
